import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';
import { Geist, Geist_Mono, Noto_Serif_KR, Parisienne } from 'next/font/google';
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const notoSerifKr = Noto_Serif_KR({
  subsets: ['latin'],
  weight: ['600'], // semibold(600) 두께를 가져옵니다.
  variable: '--font-noto-serif',
});

const parisienne = Parisienne({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-parisienne',
});

const pretendard = localFont({
  src: [
    {
      path: '../../node_modules/pretendard/dist/web/static/woff2/Pretendard-Regular.woff2',
      weight: '400',
    },
    {
      path: '../../node_modules/pretendard/dist/web/static/woff2/Pretendard-Bold.woff2',
      weight: '700',
    },
  ],
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifKr.variable} ${parisienne.variable} ${pretendard.variable} bg-background relative`}
      >
        <div className="main-container">
          <Header />
          <main>{children}</main> 
        </div>
      </body>
    </html>
  );
}
